version: '3'
services:
  apigateway:
    image: accteama/apigateway
    ports:
      - 8888:8888
    networks:
      - msa-network

  eureka:
    image: accteama/eureka:latest
    ports:
      - 8761:8761
    networks:
      - msa-network

  contents:
    image: gwangjang/reserve
    depends_on:
      - eureka
      - apigateway
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://3.38.233.119:8761/eureka/
    ports:
      - 8084:8084
    networks:
      - msa-network

networks:
  msa-network:
    external: true
